var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/caja/config-deposito/route.js")
R.c("server/chunks/[root-of-the-server]__32782744._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/node_modules_bcryptjs_index_42ebb250.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_f79f9c23._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/_next-internal_server_app_api_caja_config-deposito_route_actions_54d14578.js")
R.m(4128)
module.exports=R.m(4128).exports
