var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/produccion/planificacion/route.js")
R.c("server/chunks/[root-of-the-server]__86ea9485._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_9c34318b.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_f79f9c23._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_bcryptjs_index_42ebb250.js")
R.c("server/chunks/_next-internal_server_app_api_produccion_planificacion_route_actions_2a1b7808.js")
R.m(47914)
module.exports=R.m(47914).exports
