var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/insumos/[id]/historial/route.js")
R.c("server/chunks/[root-of-the-server]__ff71fc52._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_bcryptjs_index_42ebb250.js")
R.c("server/chunks/_f79f9c23._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/_next-internal_server_app_api_insumos_[id]_historial_route_actions_9e85e66d.js")
R.m(6062)
module.exports=R.m(6062).exports
