var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/reportes/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__03eb0b36._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_8d3e0069._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ee260829._.js")
R.c("server/chunks/ssr/node_modules_next_dist_07951b80._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_d398cf59._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_84926cca._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_reportes_page_actions_27e5da3d.js")
R.m(5514)
module.exports=R.m(5514).exports
