var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/reportes/performance/route.js")
R.c("server/chunks/[root-of-the-server]__2861d3a2._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_bcryptjs_index_42ebb250.js")
R.c("server/chunks/_f79f9c23._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/_next-internal_server_app_api_reportes_performance_route_actions_eec45e30.js")
R.m(57859)
module.exports=R.m(57859).exports
