var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/lotes/route.js")
R.c("server/chunks/[root-of-the-server]__5080a74a._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/node_modules_bcryptjs_index_42ebb250.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_f79f9c23._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/_next-internal_server_app_api_lotes_route_actions_0bca8b8c.js")
R.m(71692)
module.exports=R.m(71692).exports
