var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/costos/categorias/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__63f22753._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_45edfc91._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ee260829._.js")
R.c("server/chunks/ssr/node_modules_next_dist_07951b80._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_d398cf59._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_84926cca._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_costos_categorias_page_actions_3325220e.js")
R.m(53382)
module.exports=R.m(53382).exports
