// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/caja/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/caja">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/caja/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clientes">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/compras/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compras">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/compras/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/costos/categorias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/costos/categorias">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/costos/categorias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/costos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/costos">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/costos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/importar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/importar">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/importar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/insumos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/insumos">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/insumos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/logistica/choferes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistica/choferes">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/logistica/choferes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/logistica/flota/asignacion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistica/flota/asignacion">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/logistica/flota/asignacion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/logistica/flota/gastos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistica/flota/gastos">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/logistica/flota/gastos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/logistica/flota/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistica/flota">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/logistica/flota/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/logistica/flota/vehiculos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistica/flota/vehiculos/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/logistica/flota/vehiculos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/logistica/flota/vehiculos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistica/flota/vehiculos">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/logistica/flota/vehiculos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/logistica/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistica">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/logistica/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/logistica/repartos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistica/repartos">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/logistica/repartos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/logistica/rutas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logistica/rutas">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/logistica/rutas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/pedidos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pedidos">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/pedidos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/produccion-v2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/produccion-v2">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/produccion-v2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/produccion/historial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/produccion/historial">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/produccion/historial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/produccion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/produccion">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/produccion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/produccion/posicionamiento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/produccion/posicionamiento">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/produccion/posicionamiento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/productos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/productos/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/productos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/productos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/productos">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/productos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/proveedores/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proveedores/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/proveedores/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/proveedores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proveedores">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/proveedores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/reportes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reportes">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/reportes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empleados/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empleados/[id]">> = Specific
  const handler = {} as typeof import("../../app/empleados/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empleados/[id]/uniformes/imprimir/[entregaId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empleados/[id]/uniformes/imprimir/[entregaId]">> = Specific
  const handler = {} as typeof import("../../app/empleados/[id]/uniformes/imprimir/[entregaId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empleados/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empleados/analytics">> = Specific
  const handler = {} as typeof import("../../app/empleados/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empleados/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empleados">> = Specific
  const handler = {} as typeof import("../../app/empleados/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/geocode-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/geocode-all">> = Specific
  const handler = {} as typeof import("../../app/api/admin/geocode-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/areas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/areas">> = Specific
  const handler = {} as typeof import("../../app/api/areas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/caja/conceptos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/caja/conceptos">> = Specific
  const handler = {} as typeof import("../../app/api/caja/conceptos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/caja/config-deposito/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/caja/config-deposito">> = Specific
  const handler = {} as typeof import("../../app/api/caja/config-deposito/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/caja/rendiciones/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/caja/rendiciones">> = Specific
  const handler = {} as typeof import("../../app/api/caja/rendiciones/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/caja/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/caja">> = Specific
  const handler = {} as typeof import("../../app/api/caja/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/caja/saldos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/caja/saldos">> = Specific
  const handler = {} as typeof import("../../app/api/caja/saldos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/caja/transferir/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/caja/transferir">> = Specific
  const handler = {} as typeof import("../../app/api/caja/transferir/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clientes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clientes/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/clientes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/clientes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clientes">> = Specific
  const handler = {} as typeof import("../../app/api/clientes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/conceptos-salariales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conceptos-salariales">> = Specific
  const handler = {} as typeof import("../../app/api/conceptos-salariales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/conceptos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conceptos">> = Specific
  const handler = {} as typeof import("../../app/api/conceptos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/mercadopago/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/mercadopago">> = Specific
  const handler = {} as typeof import("../../app/api/cron/mercadopago/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/system-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/system-check">> = Specific
  const handler = {} as typeof import("../../app/api/cron/system-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard">> = Specific
  const handler = {} as typeof import("../../app/api/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/documentos-empleado/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documentos-empleado">> = Specific
  const handler = {} as typeof import("../../app/api/documentos-empleado/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/[id]/prestamos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/[id]/prestamos">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/[id]/prestamos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/[id]/uniformes/entregas/[entregaId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/[id]/uniformes/entregas/[entregaId]">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/[id]/uniformes/entregas/[entregaId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/[id]/uniformes/entregas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/[id]/uniformes/entregas">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/[id]/uniformes/entregas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/[id]/uniformes/talles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/[id]/uniformes/talles">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/[id]/uniformes/talles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/asistencia-diaria/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/asistencia-diaria">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/asistencia-diaria/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/horas-extras-pendientes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/horas-extras-pendientes">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/horas-extras-pendientes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/inasistencias/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/inasistencias/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/inasistencias/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/inasistencias/alertas/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/inasistencias/alertas/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/inasistencias/alertas/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/inasistencias/alertas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/inasistencias/alertas">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/inasistencias/alertas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/inasistencias/detectar-ausencias/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/inasistencias/detectar-ausencias">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/inasistencias/detectar-ausencias/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/inasistencias/resumen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/inasistencias/resumen">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/inasistencias/resumen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/inasistencias/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/inasistencias">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/inasistencias/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/roles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/roles/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/roles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/roles">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/empleados/sanciones/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/empleados/sanciones">> = Specific
  const handler = {} as typeof import("../../app/api/empleados/sanciones/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/entregas/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/entregas/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/entregas/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/evaluaciones/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evaluaciones">> = Specific
  const handler = {} as typeof import("../../app/api/evaluaciones/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/familias-insumo/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/familias-insumo/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/familias-insumo/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/familias-insumo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/familias-insumo">> = Specific
  const handler = {} as typeof import("../../app/api/familias-insumo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/feriados/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feriados">> = Specific
  const handler = {} as typeof import("../../app/api/feriados/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/fichadas/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fichadas/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/fichadas/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/fichadas/importar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fichadas/importar">> = Specific
  const handler = {} as typeof import("../../app/api/fichadas/importar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/fichadas/justificar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fichadas/justificar">> = Specific
  const handler = {} as typeof import("../../app/api/fichadas/justificar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/fichadas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fichadas">> = Specific
  const handler = {} as typeof import("../../app/api/fichadas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/fichas-tecnicas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fichas-tecnicas">> = Specific
  const handler = {} as typeof import("../../app/api/fichas-tecnicas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/flota/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flota/dashboard">> = Specific
  const handler = {} as typeof import("../../app/api/flota/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/flota/kilometrajes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flota/kilometrajes">> = Specific
  const handler = {} as typeof import("../../app/api/flota/kilometrajes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/flota/mantenimientos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flota/mantenimientos/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/flota/mantenimientos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/flota/mantenimientos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flota/mantenimientos">> = Specific
  const handler = {} as typeof import("../../app/api/flota/mantenimientos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/flota/vehiculos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flota/vehiculos/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/flota/vehiculos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/flota/vehiculos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flota/vehiculos">> = Specific
  const handler = {} as typeof import("../../app/api/flota/vehiculos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/flota/vencimientos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flota/vencimientos/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/flota/vencimientos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/flota/vencimientos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flota/vencimientos">> = Specific
  const handler = {} as typeof import("../../app/api/flota/vencimientos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gastos/categorias/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gastos/categorias/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/gastos/categorias/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gastos/categorias/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gastos/categorias">> = Specific
  const handler = {} as typeof import("../../app/api/gastos/categorias/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gastos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gastos">> = Specific
  const handler = {} as typeof import("../../app/api/gastos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/geocode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geocode">> = Specific
  const handler = {} as typeof import("../../app/api/geocode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/importar-pedidos-local/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/importar-pedidos-local/confirm">> = Specific
  const handler = {} as typeof import("../../app/api/importar-pedidos-local/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/importar-pedidos-local/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/importar-pedidos-local/preview">> = Specific
  const handler = {} as typeof import("../../app/api/importar-pedidos-local/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/importar-pedidos/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/importar-pedidos/confirm">> = Specific
  const handler = {} as typeof import("../../app/api/importar-pedidos/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/importar-pedidos/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/importar-pedidos/preview">> = Specific
  const handler = {} as typeof import("../../app/api/importar-pedidos/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/insumos/[id]/historial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/insumos/[id]/historial">> = Specific
  const handler = {} as typeof import("../../app/api/insumos/[id]/historial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/insumos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/insumos/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/insumos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/insumos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/insumos">> = Specific
  const handler = {} as typeof import("../../app/api/insumos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/licencias/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/licencias">> = Specific
  const handler = {} as typeof import("../../app/api/licencias/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/liquidaciones-finales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/liquidaciones-finales">> = Specific
  const handler = {} as typeof import("../../app/api/liquidaciones-finales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/liquidaciones/borrador/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/liquidaciones/borrador">> = Specific
  const handler = {} as typeof import("../../app/api/liquidaciones/borrador/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/liquidaciones/final/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/liquidaciones/final">> = Specific
  const handler = {} as typeof import("../../app/api/liquidaciones/final/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/liquidaciones/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/liquidaciones/preview">> = Specific
  const handler = {} as typeof import("../../app/api/liquidaciones/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/liquidaciones/reporte/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/liquidaciones/reporte">> = Specific
  const handler = {} as typeof import("../../app/api/liquidaciones/reporte/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/liquidaciones/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/liquidaciones">> = Specific
  const handler = {} as typeof import("../../app/api/liquidaciones/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/liquidaciones/sac/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/liquidaciones/sac">> = Specific
  const handler = {} as typeof import("../../app/api/liquidaciones/sac/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/liquidaciones/vacaciones/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/liquidaciones/vacaciones/history">> = Specific
  const handler = {} as typeof import("../../app/api/liquidaciones/vacaciones/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/liquidaciones/vacaciones/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/liquidaciones/vacaciones">> = Specific
  const handler = {} as typeof import("../../app/api/liquidaciones/vacaciones/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/logistica/choferes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logistica/choferes">> = Specific
  const handler = {} as typeof import("../../app/api/logistica/choferes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/logistica/flota/asignaciones/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logistica/flota/asignaciones">> = Specific
  const handler = {} as typeof import("../../app/api/logistica/flota/asignaciones/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/logistica/flota/gastos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logistica/flota/gastos/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/logistica/flota/gastos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/logistica/flota/gastos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logistica/flota/gastos">> = Specific
  const handler = {} as typeof import("../../app/api/logistica/flota/gastos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/lotes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lotes/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/lotes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/lotes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lotes">> = Specific
  const handler = {} as typeof import("../../app/api/lotes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mercadopago/movimientos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mercadopago/movimientos">> = Specific
  const handler = {} as typeof import("../../app/api/mercadopago/movimientos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/movimientos-producto/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/movimientos-producto">> = Specific
  const handler = {} as typeof import("../../app/api/movimientos-producto/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/movimientos-stock/[id]/pago/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/movimientos-stock/[id]/pago">> = Specific
  const handler = {} as typeof import("../../app/api/movimientos-stock/[id]/pago/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/movimientos-stock/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/movimientos-stock/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/movimientos-stock/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/movimientos-stock/factura/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/movimientos-stock/factura">> = Specific
  const handler = {} as typeof import("../../app/api/movimientos-stock/factura/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/movimientos-stock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/movimientos-stock">> = Specific
  const handler = {} as typeof import("../../app/api/movimientos-stock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pedidos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pedidos/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/pedidos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pedidos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pedidos">> = Specific
  const handler = {} as typeof import("../../app/api/pedidos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/presentaciones/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/presentaciones/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/presentaciones/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/presentaciones/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/presentaciones">> = Specific
  const handler = {} as typeof import("../../app/api/presentaciones/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/prestamos/[id]/cuotas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prestamos/[id]/cuotas">> = Specific
  const handler = {} as typeof import("../../app/api/prestamos/[id]/cuotas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/prestamos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prestamos/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/prestamos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/prestamos/cuotas/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prestamos/cuotas/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/prestamos/cuotas/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/produccion/conceptos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/produccion/conceptos/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/produccion/conceptos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/produccion/conceptos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/produccion/conceptos">> = Specific
  const handler = {} as typeof import("../../app/api/produccion/conceptos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/produccion/historial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/produccion/historial">> = Specific
  const handler = {} as typeof import("../../app/api/produccion/historial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/produccion/planificacion/descontar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/produccion/planificacion/descontar">> = Specific
  const handler = {} as typeof import("../../app/api/produccion/planificacion/descontar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/produccion/planificacion/importar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/produccion/planificacion/importar">> = Specific
  const handler = {} as typeof import("../../app/api/produccion/planificacion/importar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/produccion/planificacion/manual/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/produccion/planificacion/manual">> = Specific
  const handler = {} as typeof import("../../app/api/produccion/planificacion/manual/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/produccion/planificacion/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/produccion/planificacion">> = Specific
  const handler = {} as typeof import("../../app/api/produccion/planificacion/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/produccion/posicionamiento/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/produccion/posicionamiento">> = Specific
  const handler = {} as typeof import("../../app/api/produccion/posicionamiento/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/productos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/productos/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/productos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/productos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/productos">> = Specific
  const handler = {} as typeof import("../../app/api/productos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/proveedores/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proveedores/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/proveedores/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/proveedores/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proveedores">> = Specific
  const handler = {} as typeof import("../../app/api/proveedores/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/puestos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/puestos">> = Specific
  const handler = {} as typeof import("../../app/api/puestos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/realtime/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/realtime/events">> = Specific
  const handler = {} as typeof import("../../app/api/realtime/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reportes/alertas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reportes/alertas">> = Specific
  const handler = {} as typeof import("../../app/api/reportes/alertas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reportes/caja/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reportes/caja">> = Specific
  const handler = {} as typeof import("../../app/api/reportes/caja/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reportes/categorias/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reportes/categorias">> = Specific
  const handler = {} as typeof import("../../app/api/reportes/categorias/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reportes/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reportes/config">> = Specific
  const handler = {} as typeof import("../../app/api/reportes/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reportes/costos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reportes/costos">> = Specific
  const handler = {} as typeof import("../../app/api/reportes/costos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reportes/desperdicio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reportes/desperdicio">> = Specific
  const handler = {} as typeof import("../../app/api/reportes/desperdicio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reportes/detalle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reportes/detalle">> = Specific
  const handler = {} as typeof import("../../app/api/reportes/detalle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reportes/metadata/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reportes/metadata">> = Specific
  const handler = {} as typeof import("../../app/api/reportes/metadata/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reportes/performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reportes/performance">> = Specific
  const handler = {} as typeof import("../../app/api/reportes/performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reportes/preferencias/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reportes/preferencias">> = Specific
  const handler = {} as typeof import("../../app/api/reportes/preferencias/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reportes/produccion/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reportes/produccion">> = Specific
  const handler = {} as typeof import("../../app/api/reportes/produccion/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reportes/rentabilidad/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reportes/rentabilidad">> = Specific
  const handler = {} as typeof import("../../app/api/reportes/rentabilidad/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reportes/rrhh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reportes/rrhh">> = Specific
  const handler = {} as typeof import("../../app/api/reportes/rrhh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reportes/ventas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reportes/ventas">> = Specific
  const handler = {} as typeof import("../../app/api/reportes/ventas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas/auto-assign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas/auto-assign">> = Specific
  const handler = {} as typeof import("../../app/api/rutas/auto-assign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas/optimize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas/optimize">> = Specific
  const handler = {} as typeof import("../../app/api/rutas/optimize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rutas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rutas">> = Specific
  const handler = {} as typeof import("../../app/api/rutas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stock-producto/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stock-producto">> = Specific
  const handler = {} as typeof import("../../app/api/stock-producto/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/turnos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/turnos">> = Specific
  const handler = {} as typeof import("../../app/api/turnos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ubicaciones/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ubicaciones">> = Specific
  const handler = {} as typeof import("../../app/api/ubicaciones/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/uniformes/imprimir/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uniformes/imprimir">> = Specific
  const handler = {} as typeof import("../../app/api/uniformes/imprimir/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/uniformes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uniformes">> = Specific
  const handler = {} as typeof import("../../app/api/uniformes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/mercadopago/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/mercadopago">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/mercadopago/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/uploads/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/uploads/[...path]">> = Specific
  const handler = {} as typeof import("../../app/uploads/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/empleados/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/empleados">> = Specific
  const handler = {} as typeof import("../../app/empleados/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
