var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/logistica/flota/asignaciones/route.js")
R.c("server/chunks/[root-of-the-server]__cbde0217._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/node_modules_bcryptjs_index_42ebb250.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_f79f9c23._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/ce889_server_app_api_logistica_flota_asignaciones_route_actions_97c14086.js")
R.m(6758)
module.exports=R.m(6758).exports
