var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/empleados/analytics/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__9e7923a5._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_4897b421._.js")
R.c("server/chunks/ssr/[root-of-the-server]__ee260829._.js")
R.c("server/chunks/ssr/node_modules_next_dist_07951b80._.js")
R.c("server/chunks/ssr/node_modules_next_dist_6607e1c8._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_d398cf59._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_e45b91d8._.js")
R.c("server/chunks/ssr/_next-internal_server_app_empleados_analytics_page_actions_f2a42bbf.js")
R.m(2647)
module.exports=R.m(2647).exports
