var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/reportes/preferencias/route.js")
R.c("server/chunks/[root-of-the-server]__8b7240b8._.js")
R.c("server/chunks/[root-of-the-server]__68e18c0a._.js")
R.c("server/chunks/node_modules_bcryptjs_index_42ebb250.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/_f79f9c23._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_next_dist_3cae5f3a._.js")
R.c("server/chunks/_4dfa609f._.js")
R.c("server/chunks/_next-internal_server_app_api_reportes_preferencias_route_actions_fbea5457.js")
R.m(14400)
module.exports=R.m(14400).exports
